
export const productSlides = [
  {
    id: 1,
    image: "/assets/images/watch.svg",
    cartIcon: "/assets/icons/cart-btn.svg",
    description: "Black Automatic Watch",
    price: "$169.99",
    bottomText: "Accessories",
    bottomImage: "/assets/icons/price.svg",
    starIcon: "/assets/icons/star.svg",
    rating: "4.9 (98)",
  },
  {
    id: 2,
    image: "/assets/images/watch.svg",
    cartIcon: "/assets/icons/cart-btn.svg",
    description: "Black Automatic Watch",
    price: "$169.99",
    bottomText: "Accessories",
    bottomImage: "/assets/icons/price.svg",
    starIcon: "/assets/icons/star.svg",
    rating: "4.9 (98)",
  },
   {
    id: 3,
    image: "/assets/images/watch.svg",
    cartIcon: "/assets/icons/cart-btn.svg",
    description: "Black Automatic Watch",
    price: "$169.99",
    bottomText: "Accessories",
    bottomImage: "/assets/icons/price.svg",
    starIcon: "/assets/icons/star.svg",
    rating: "4.9 (98)",
  },
   {
    id: 4,
    image: "/assets/images/watch.svg",
    cartIcon: "/assets/icons/cart-btn.svg",
    description: "Black Automatic Watch",
    price: "$169.99",
    bottomText: "Accessories",
    bottomImage: "/assets/icons/price.svg",
    starIcon: "/assets/icons/star.svg",
    rating: "4.9 (98)",
  },
];
